### ISSUE TITLE
udp suggestions

### ISSUE THREAD

**Issue by SergejJurecko** [aetrion/erl-dns#37]
I've been looking at the udp code and I have some suggestions. 

Use: {recbuf,1024*1024} on gen_udp:open
The UDP socket receive buffer can fill up surprisingly quickly and the default is dangerously low.

Use {active,100} or similar for receiving packets. It improves throughput. 

Use inet_udp:send instead of gen_udp:send. If gen_udp:send is used, inet:getaddrs/3 will be called on every send. This causes a needless erlang:start_timer and erlang:cancel_timer call.

**Comment by aeden** [comment]
Thanks for the suggestions.

Given `{active, once}` mode, the larger buffer is essentially unnecessary since there will only be one packet in the buffer at any given time, correct? The typical DNS packet size is 512 bytes, unless EDNS specifies a larger size. Even in that case the typical packet size will still be less than the default 8k size used in Erlang.

So in the current setup the default buffer size is fine.

Now, let's consider if I switched to `{active, 100}`. In this case the buffer size would need to be larger. My understanding of `{active, N}`, based on http://www.erlang.org/doc/man/inet.html#setopts-2 , I would need to also listen for the `{udp_passive, Socket}` message and set `{active, N}` again. I'm not sure how much of a gain we'd get by letting the socket buffer, but I may try some testing.

Finally, regarding `inet_udp:send` versus `gen_udp:send`, are there any drawbacks?

**Comment by SergejJurecko** [comment]
About buffers you are very wrong. This is kernel space reserved for
incomming packets. Nothing to do with active setting.

Once it is full (because they were not processed fast enough) every arrived
udp packet is dropped. I had this problem on every project I used udp in
erlang. It was always filling up.

The difference in inet_udp is that IPs must be in tuple form. That timer is
so that it tries to resolve address in list form. But if it is tuple it
just sets timer, noop then cancel. Unfortunate design.

**Comment by aeden** [comment]
Implemented two of the three suggested changes with #61
